name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Build, Test, Generate and Deploy
    env:
      DOTNET_ENVIRONMENT: Production
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build -c Release

      - name: Publish application
        run: dotnet publish ./Notes/Notes.fsproj -c Release -o ./publish

      - name: Execute generation
        run: ./publish/Notes

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_OCEAN_0B7825E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "/homepage"
          api_location: ""
          output_location: ""